#!/usr/bin/python
# encoding=UTF-8

# Copyright © 2014-2016 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

from __future__ import print_function

import ConfigParser as configparser
import argparse
import os
import shutil
import subprocess as ipc
import tempfile

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('directory', metavar='<directory>')
    ap.add_argument('-o', '--output-file', metavar='<output-file>', default='a.out')
    options = ap.parse_args()
    sonames = set()
    os.stat(os.path.join(options.directory, ''))
    for directory, _, filenames in os.walk(options.directory):
        for filename in filenames:
            if not filename.endswith('.dctypes'):
                continue
            path = os.path.join(directory, filename)
            cp = configparser.RawConfigParser()
            with open(path) as file:
                cp.readfp(file)
                for _, soname in cp.items('find_library'):
                    sonames.add(soname)
    tmpdir = tempfile.mkdtemp(prefix='dctypes.')
    try:
        with open(tmpdir + '/libeverything.so', 'w') as devlib:
            for soname in sonames:
                print('INPUT({soname})'.format(soname=soname), file=devlib)
        ipc.check_call([
            'gcc', '-shared', '-nostdlib',
            '-Wl,--no-as-needed',
            '-L', tmpdir, '-leverything',
            '-o', options.output_file
        ])
    finally:
        shutil.rmtree(tmpdir)

if __name__ == '__main__':
    main()

# vim:ts=4 sts=4 sw=4 et
